INSERT INTO public.venue (id, address, capacity, city, details, email, name, phone, price) VALUES (1, 'st. Al-Farabi, 40', 150, 'Almaty', e'Best restaurant in the city!
', 'cityrestaurant@almaty.kz', 'Almaty City Restaurant ', '+77077070100', 40);
INSERT INTO public.venue (id, address, capacity, city, details, email, name, phone, price) VALUES (2, 'st. Kenesaty Khan, 83/1', 35, 'Almaty', 'Best modern lounge bar in the city!', 'hploungebar@email.com', 'HP lounge Bar', '+77077070101', 20);

insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (3, 'Lueilwitz Group', 'Almaty', '66606 Mosinee Circle', 'alukehurst2@lycos.com', '+77019578336', 364, 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 23);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (4, 'Kulas LLC', 'Almaty', '76 Eggendart Road', 'mkrzysztof3@w3.org', '+77019300243', 99, 'Integer tincidunt ante vel ipsum.', 87);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (5, 'Haag Inc', 'Almaty', '7922 Dryden Hill', 'mstirland4@webnode.com', '+77016024290', 113, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 133);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (6, 'Erdman Group', 'Almaty', '11 Lien Point', 'eeisold5@linkedin.com', '+77016778287', 34, 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', 102);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (7, 'Mosciski Group', 'Almaty', '63717 Southridge Street', 'sadiscot6@amazon.co.uk', '+77013238483', 478, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 62);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (8, 'Hammes-Langworth', 'Almaty', '3 Superior Junction', 'gmccaughey7@edublogs.org', '+77012536812', 471, 'Cras non velit nec nisi vulputate nonummy.', 25);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (9, 'Rath-Russel', 'Almaty', '3434 Prairie Rose Road', 'jcauldwell8@virginia.edu', '+77012472914', 399, 'Nulla mollis molestie lorem.', 42);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (10, 'Quitzon-Luettgen', 'Almaty', '9 Logan Lane', 'cgeist9@printfriendly.com', '+77013660717', 414, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. ', 182);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (11, 'Beatty-Douglas', 'Almaty', '94265 Amoth Crossing', 'aescolmea@ibm.com', '+77014865552', 136, 'Etiam faucibus cursus urna.', 55);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (12, 'Mohr-Stoltenberg', 'Almaty', '4 Maple Wood Place', 'kschollb@symantec.com', '+77019707069', 243, 'Nunc rhoncus dui vel sem.', 54);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (13, 'Flatley-Considine', 'Almaty', '42 Crest Line Street', 'aalderseac@gmpg.org', '+77017458756', 206, 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 60);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (14, 'Schulist Inc', 'Almaty', '286 Redwing Hill', 'gcherringtond@cargocollective.com', '+77012003594', 186, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 169);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (15, 'Dickinson Group', 'Almaty', '95 Main Hill', 'hcristoforoe@jimdo.com', '+77019136091', 41, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 87);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (16, 'Bernhard, Pouros and Hansen', 'Almaty', '3 Corben Plaza', 'loldcotef@storify.com', '+77012061672', 415, 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. ', 130);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (17, 'Rowe-West', 'Almaty', '87 Russell Park', 'dosiaghailg@who.int', '+77014623185', 202, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ', 68);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (18, 'Rath, Rolfson and Kerluke', 'Almaty', '958 Hoffman Road', 'bandrettih@flavors.me', '+77012740561', 89, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. ', 140);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (19, 'Powlowski, Brown and DuBuque', 'Almaty', '50208 Warbler Way', 'gballisteri@yellowpages.com', '+77015958915', 456, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 73);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (20, 'Schmeler and Sons', 'Almaty', '4 Fallview Alley', 'emcdermidj@comsenz.com', '+77016049079', 222, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. ', 76);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (21, 'Ward-Fisher', 'Almaty', '173 Quincy Hill', 'hbeastallk@java.com', '+77013444243', 177, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. ', 91);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (22, 'Wunsch and Sons', 'Almaty', '73487 Walton Court', 'ctodaril@walmart.com', '+77016204613', 146, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 147);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (23, 'Thompson, Lemke and Windler', 'Almaty', '505 Holmberg Way', 'hcoomesm@businessinsider.com', '+77017834918', 418, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 52);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (24, 'Mayer-Jacobson', 'Almaty', '6 Transport Lane', 'hlahyn@multiply.com', '+77015865558', 242, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', 105);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (25, 'Osinski-Kreiger', 'Almaty', '73 Artisan Crossing', 'tstruttono@flavors.me', '+77013775011', 104, 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', 171);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (26, 'Quitzon, Wiegand and Heller', 'Almaty', '1 Buell Crossing', 'hfullom0@mail.ru', '+77014268623', 418, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. ', 51);
insert into public.venue (id, name, city, address, email, phone, capacity, details, price) values (27, 'Schimmel, Bode and Barton', 'Almaty', '7 Autumn Leaf Avenue', 'adoggrell1@sohu.com', '+77012111238', 43, 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; ', 170);
